port: 162
stats:
  subject: stats.test
  interval: 10s
nats: 
  url: nats://127.0.0.1:4222
  subject: itsa.trap
  creds-file: ""
users:
  - user: someUsername
    auth-alg: SHA
    auth-passwd: mySecureAuthPassword
    priv-alg: AES
    priv-passwd: mySecurePrivPassword
